# Generated by Django 2.0.7 on 2018-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('picture', models.FileField(upload_to='')),
                ('phoneNo', models.CharField(default='+255 687 340 202', max_length=20)),
                ('linkedin', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Team members',
            },
        ),
    ]
