# Generated by Django 2.0.6 on 2018-07-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phoneNo',
            field=models.CharField(default='+255 687 340 202', max_length=20),
        ),
    ]
