# Generated by Django 2.0.5 on 2018-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.FileField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('phoneno', models.CharField(max_length=128)),
                ('faxno', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('plot', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('facebook', models.CharField(max_length=128)),
                ('twitter', models.CharField(max_length=128)),
                ('linkedin', models.CharField(max_length=128)),
                ('pinterest', models.CharField(max_length=128)),
                ('googleplus', models.CharField(max_length=128)),
                ('instagram', models.CharField(max_length=128)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('motto', models.TextField()),
                ('objective', models.TextField()),
                ('values', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Company details',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
