# Generated by Django 2.0.5 on 2018-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='testimony',
            field=models.TextField(default='Seastone is a great real estate company.'),
        ),
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(default='Customer', max_length=128),
        ),
    ]
