# Generated by Django 2.0.6 on 2018-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180624_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=256)),
                ('twitter', models.CharField(max_length=256)),
                ('linkedin', models.CharField(max_length=256)),
                ('instagram', models.CharField(max_length=256)),
                ('interests', models.CharField(max_length=256)),
                ('extracurriculars', models.CharField(max_length=256)),
                ('department', models.CharField(choices=[('agency', 'Agency'), ('management', 'Property Management'), ('valuation', 'Valuation'), ('devt', 'Property development'), ('survey', 'Architecture and Quantity survey'), ('landscaping', 'Landscaping and Lawn-care'), ('facilities', 'Facilities management'), ('analysis', 'Investment analysis'), ('furniture', 'Furniture, Fixture and Fitting'), ('planning', 'Urban and Rural planning'), ('assesment', 'Environmetal and Social Impact assesment'), ('land-survey', 'Land Survey')], default='agency', max_length=64)),
            ],
        ),
    ]
