# Generated by Django 2.0.7 on 2018-07-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_careers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name': 'Internship Request', 'verbose_name_plural': 'Internship Requests'},
        ),
        migrations.AlterField(
            model_name='careers',
            name='department',
            field=models.CharField(choices=[('agency', 'Agency'), ('management', 'Property Management'), ('valuation', 'Valuation'), ('devt', 'Property development'), ('survey', 'Architecture and Quantity survey'), ('landscaping', 'Landscaping and Lawn-care'), ('facilities', 'Facilities management'), ('analysis', 'Investment analysis'), ('furniture', 'Furniture, Fixture and Fitting'), ('planning', 'Urban and Rural planning'), ('assesment', 'Environmental and Social Impact assessment'), ('land-survey', 'Land Survey')], max_length=64),
        ),
    ]
