# Generated by Django 2.0.5 on 2018-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Message from')),
                ('phoneNo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
