# Generated by Django 2.0.5 on 2018-06-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerMessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Customer Messages', 'verbose_name_plural': 'Messages'},
        ),
    ]
