# Generated by Django 2.0.6 on 2018-06-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerMessages', '0002_auto_20180626_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Customer Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='request',
            name='phoneNo',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
