# Generated by Django 2.0.5 on 2018-06-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=64)),
                ('slug', models.SlugField(default='title-slug', unique=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Size of Property(Sq M)')),
                ('bedNo', models.IntegerField(verbose_name='Number of Bedrooms')),
                ('bathNo', models.IntegerField(verbose_name='Number of Bathrooms')),
                ('features', models.TextField(verbose_name='Property Features')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('type_of_property', models.CharField(choices=[('SALE', 'For sale'), ('RENT', 'For rent')], default='SALE', max_length=25)),
                ('status_of_property', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=25)),
                ('location', models.CharField(default='location', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Price(in $)')),
                ('featured', models.CharField(choices=[('YES', 'Featured'), ('NO', 'Not Featured')], default='YES', max_length=5)),
                ('uploader', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media_cdn/commercial_farming.jpeg', upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.Property')),
            ],
        ),
    ]
