# Generated by Django 2.0.5 on 2018-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Dar es salaam', max_length=64),
        ),
    ]
